(* autogenerated from vault-plugin-database-clickhouse/internal/deletepath *)
From New.golang Require Import defn.
Module pkg_id.
Definition deletepath : go_string := "vault-plugin-database-clickhouse/internal/deletepath".

End pkg_id.
Export pkg_id.
Module deletepath.

Definition UseCustomRevocation {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/deletepath.UseCustomRevocation"%go.

Definition testUseCustomRevocationFalseForEmpty {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/deletepath.testUseCustomRevocationFalseForEmpty"%go.

Definition testUseCustomRevocationTrueWhenProvided {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/deletepath.testUseCustomRevocationTrueWhenProvided"%go.

(* UseCustomRevocation reports whether DeleteUser should run role revocation statements.

   go: path.go:4:6 *)
Definition UseCustomRevocationⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "commands",
    exception_do (let: "commands" := (GoAlloc (go.SliceType go.string) "commands") in
    return: ((let: "$a0" := (![go.SliceType go.string] "commands") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0") >⟨go.int⟩ #(W64 0))).

(* testUseCustomRevocationFalseForEmpty commands list.

   go: semantics.go:4:6 *)
Definition testUseCustomRevocationFalseForEmptyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((⟨go.bool⟩! (let: "$a0" := (Convert go.untyped_nil (go.SliceType go.string) UntypedNil) in
     (FuncResolve UseCustomRevocation [] #()) "$a0")))).

(* testUseCustomRevocationTrueWhenProvided commands list.

   go: semantics.go:9:6 *)
Definition testUseCustomRevocationTrueWhenProvidedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (let: "$a0" := (let: "$v0" := #"DROP USER"%go in
     CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0")])) in
     (FuncResolve UseCustomRevocation [] #()) "$a0")).

#[global] Instance info' : PkgInfo pkg_id.deletepath :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.deletepath (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] UseCustomRevocation_unfold :: FuncUnfold UseCustomRevocation [] (UseCustomRevocationⁱᵐᵖˡ);
  #[global] testUseCustomRevocationFalseForEmpty_unfold :: FuncUnfold testUseCustomRevocationFalseForEmpty [] (testUseCustomRevocationFalseForEmptyⁱᵐᵖˡ);
  #[global] testUseCustomRevocationTrueWhenProvided_unfold :: FuncUnfold testUseCustomRevocationTrueWhenProvided [] (testUseCustomRevocationTrueWhenProvidedⁱᵐᵖˡ);
}.
End deletepath.
