(* autogenerated from vault-plugin-database-clickhouse/internal/firsterror *)
From New.golang Require Import defn.
Module pkg_id.
Definition firsterror : go_string := "vault-plugin-database-clickhouse/internal/firsterror".

End pkg_id.
Export pkg_id.
Module firsterror.

Definition FirstError {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/firsterror.FirstError"%go.

Definition nilStep {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/firsterror.nilStep"%go.

Definition testFirstErrorStops {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/firsterror.testFirstErrorStops"%go.

Definition testFirstErrorAllSuccess {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/firsterror.testFirstErrorAllSuccess"%go.

Definition testFirstErrorPreserved {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/firsterror.testFirstErrorPreserved"%go.

(* FirstError runs f on each string in order and returns the first error from f.

   go: firsterror.go:4:6 *)
Definition FirstErrorⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "xs" "f",
    exception_do (let: "f" := (GoAlloc (go.FunctionType (go.Signature [go.string] false [go.error])) "f") in
    let: "xs" := (GoAlloc (go.SliceType go.string) "xs") in
    let: "$range" := (![go.SliceType go.string] "xs") in
    (let: "x" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("x" <-[go.string] "$value");;;
      do:  "$key";;;
      (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: "$r0" := (let: "$a0" := (![go.string] "x") in
      (![go.FunctionType (go.Signature [go.string] false [go.error])] "f") "$a0") in
      do:  ("err" <-[go.error] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then return: (![go.error] "err")
      else do:  #()))));;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* go: semantics.go:3:6 *)
Definition nilStepⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (Convert go.untyped_nil go.error UntypedNil)).

(* testFirstErrorStops reports nilStep returns nil.

   go: semantics.go:6:6 *)
Definition testFirstErrorStopsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := #"x"%go in
     (FuncResolve nilStep [] #()) "$a0") =⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

(* testFirstErrorAllSuccess reports nilStep returns nil on empty input.

   go: semantics.go:11:6 *)
Definition testFirstErrorAllSuccessⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := #""%go in
     (FuncResolve nilStep [] #()) "$a0") =⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

(* testFirstErrorPreserved reports nilStep returns nil for any input.

   go: semantics.go:16:6 *)
Definition testFirstErrorPreservedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := #"a"%go in
     (FuncResolve nilStep [] #()) "$a0") =⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

#[global] Instance info' : PkgInfo pkg_id.firsterror :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.firsterror (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] FirstError_unfold :: FuncUnfold FirstError [] (FirstErrorⁱᵐᵖˡ);
  #[global] nilStep_unfold :: FuncUnfold nilStep [] (nilStepⁱᵐᵖˡ);
  #[global] testFirstErrorStops_unfold :: FuncUnfold testFirstErrorStops [] (testFirstErrorStopsⁱᵐᵖˡ);
  #[global] testFirstErrorAllSuccess_unfold :: FuncUnfold testFirstErrorAllSuccess [] (testFirstErrorAllSuccessⁱᵐᵖˡ);
  #[global] testFirstErrorPreserved_unfold :: FuncUnfold testFirstErrorPreserved [] (testFirstErrorPreservedⁱᵐᵖˡ);
}.
End firsterror.
