(* autogenerated from vault-plugin-database-clickhouse/internal/stmt *)
Require Export New.code.strings.
From New.golang Require Import defn.
Module pkg_id.
Definition stmt : go_string := "vault-plugin-database-clickhouse/internal/stmt".

End pkg_id.
Export pkg_id.
Module stmt.

Definition NormalizeCommands {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.NormalizeCommands"%go.

Definition normalizeStatement {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.normalizeStatement"%go.

Definition splitSemicolon {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.splitSemicolon"%go.

Definition StatementsOrDefault {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.StatementsOrDefault"%go.

Definition testNormalizeIdempotent {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.testNormalizeIdempotent"%go.

Definition testNormalizeIdempotentEmpty {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.testNormalizeIdempotentEmpty"%go.

Definition testStatementsOrDefaultFallback {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.testStatementsOrDefaultFallback"%go.

Definition testStatementsOrDefaultProvided {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.testStatementsOrDefaultProvided"%go.

(* NormalizeCommands splits each command on semicolons, trims whitespace, and drops empty parts.

   go: normalize.go:6:6 *)
Definition NormalizeCommandsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "commands",
    exception_do (let: "commands" := (GoAlloc (go.SliceType go.string) "commands") in
    let: "out" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$range" := (![go.SliceType go.string] "commands") in
    (let: "cmd" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("cmd" <-[go.string] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "out") in
      let: "$a1" := (let: "$a0" := (![go.string] "cmd") in
      (FuncResolve normalizeStatement [] #()) "$a0") in
      (FuncResolve go.append [go.SliceType go.string] #()) "$a0" "$a1") in
      do:  ("out" <-[go.SliceType go.string] "$r0")));;;
    return: (![go.SliceType go.string] "out")).

(* go: normalize.go:14:6 *)
Definition normalizeStatementⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "stmt",
    exception_do (let: "stmt" := (GoAlloc go.string "stmt") in
    let: "out" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$range" := (let: "$a0" := (![go.string] "stmt") in
    (FuncResolve splitSemicolon [] #()) "$a0") in
    (let: "part" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("part" <-[go.string] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![go.string] "part") in
      (FuncResolve strings.TrimSpace [] #()) "$a0") in
      do:  ("part" <-[go.string] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.string] "part") ≠⟨go.string⟩ #""%go)
      then
        let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "out") in
        let: "$a1" := ((let: "$sl0" := (![go.string] "part") in
        CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$sl0")]))) in
        (FuncResolve go.append [go.SliceType go.string] #()) "$a0" "$a1") in
        do:  ("out" <-[go.SliceType go.string] "$r0")
      else do:  #())));;;
    return: (![go.SliceType go.string] "out")).

(* go: normalize.go:25:6 *)
Definition splitSemicolonⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "s",
    exception_do (let: "s" := (GoAlloc go.string "s") in
    return: (let: "$a0" := (![go.string] "s") in
     let: "$a1" := #";"%go in
     (FuncResolve strings.Split [] #()) "$a0" "$a1")).

(* StatementsOrDefault returns provided when non-empty, otherwise a single fallback statement.

   go: ordefault.go:4:6 *)
Definition StatementsOrDefaultⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "provided" "fallback",
    exception_do (let: "fallback" := (GoAlloc go.string "fallback") in
    let: "provided" := (GoAlloc (go.SliceType go.string) "provided") in
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "provided") in
    (FuncResolve go.len [go.SliceType go.string] #()) "$a0") >⟨go.int⟩ #(W64 0))
    then return: (![go.SliceType go.string] "provided")
    else do:  #());;;
    return: (let: "$v0" := (![go.string] "fallback") in
     CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0")]))).

(* testNormalizeIdempotent checks StatementsOrDefault fallback length.

   go: semantics.go:4:6 *)
Definition testNormalizeIdempotentⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := (let: "$a0" := (Convert go.untyped_nil (go.SliceType go.string) UntypedNil) in
     let: "$a1" := #"ALTER USER"%go in
     (FuncResolve StatementsOrDefault [] #()) "$a0" "$a1") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0") =⟨go.int⟩ #(W64 1))).

(* testNormalizeIdempotentEmpty checks StatementsOrDefault empty fallback length.

   go: semantics.go:9:6 *)
Definition testNormalizeIdempotentEmptyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := (let: "$a0" := (Convert go.untyped_nil (go.SliceType go.string) UntypedNil) in
     let: "$a1" := #"x"%go in
     (FuncResolve StatementsOrDefault [] #()) "$a0" "$a1") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0") =⟨go.int⟩ #(W64 1))).

(* testStatementsOrDefaultFallback uses fallback when provided is empty.

   go: semantics.go:14:6 *)
Definition testStatementsOrDefaultFallbackⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "got" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (Convert go.untyped_nil (go.SliceType go.string) UntypedNil) in
    let: "$a1" := #"ALTER USER"%go in
    (FuncResolve StatementsOrDefault [] #()) "$a0" "$a1") in
    do:  ("got" <-[go.SliceType go.string] "$r0");;;
    return: ((let: "$a0" := (![go.SliceType go.string] "got") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0") =⟨go.int⟩ #(W64 1))).

(* testStatementsOrDefaultProvided keeps non-empty provided statements.

   go: semantics.go:20:6 *)
Definition testStatementsOrDefaultProvidedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "in" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$v0" := #"CREATE USER"%go in
    CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0")])) in
    do:  ("in" <-[go.SliceType go.string] "$r0");;;
    let: "got" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "in") in
    let: "$a1" := #"ALTER USER"%go in
    (FuncResolve StatementsOrDefault [] #()) "$a0" "$a1") in
    do:  ("got" <-[go.SliceType go.string] "$r0");;;
    return: ((let: "$a0" := (![go.SliceType go.string] "got") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0") =⟨go.int⟩ (let: "$a0" := (![go.SliceType go.string] "in") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0"))).

#[global] Instance info' : PkgInfo pkg_id.stmt :=
{|
  pkg_imported_pkgs := [code.strings.pkg_id.strings]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.stmt (λ: <>,
      exception_do (do:  (strings.initialize' #()))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] NormalizeCommands_unfold :: FuncUnfold NormalizeCommands [] (NormalizeCommandsⁱᵐᵖˡ);
  #[global] normalizeStatement_unfold :: FuncUnfold normalizeStatement [] (normalizeStatementⁱᵐᵖˡ);
  #[global] splitSemicolon_unfold :: FuncUnfold splitSemicolon [] (splitSemicolonⁱᵐᵖˡ);
  #[global] StatementsOrDefault_unfold :: FuncUnfold StatementsOrDefault [] (StatementsOrDefaultⁱᵐᵖˡ);
  #[global] testNormalizeIdempotent_unfold :: FuncUnfold testNormalizeIdempotent [] (testNormalizeIdempotentⁱᵐᵖˡ);
  #[global] testNormalizeIdempotentEmpty_unfold :: FuncUnfold testNormalizeIdempotentEmpty [] (testNormalizeIdempotentEmptyⁱᵐᵖˡ);
  #[global] testStatementsOrDefaultFallback_unfold :: FuncUnfold testStatementsOrDefaultFallback [] (testStatementsOrDefaultFallbackⁱᵐᵖˡ);
  #[global] testStatementsOrDefaultProvided_unfold :: FuncUnfold testStatementsOrDefaultProvided [] (testStatementsOrDefaultProvidedⁱᵐᵖˡ);
  #[global] import_strings_Assumption :: strings.Assumptions;
}.
End stmt.
