(* autogenerated from vault-plugin-database-clickhouse/internal/stmt *)
Require Export New.code.strings.
Require Export New.code.slices.
From New.golang Require Import defn.
Module pkg_id.
Definition stmt : go_string := "vault-plugin-database-clickhouse/internal/stmt".

End pkg_id.
Export pkg_id.
Module stmt.

Definition NormalizeCommands {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.NormalizeCommands"%go.

Definition normalizeStatement {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.normalizeStatement"%go.

Definition splitSemicolon {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.splitSemicolon"%go.

Definition testNormalizeIdempotent {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.testNormalizeIdempotent"%go.

Definition testNormalizeIdempotentEmpty {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmt.testNormalizeIdempotentEmpty"%go.

(* NormalizeCommands splits each command on semicolons, trims whitespace, and drops empty parts.

   go: normalize.go:6:6 *)
Definition NormalizeCommandsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "commands",
    exception_do (let: "commands" := (GoAlloc (go.SliceType go.string) "commands") in
    let: "out" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$range" := (![go.SliceType go.string] "commands") in
    (let: "cmd" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("cmd" <-[go.string] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "out") in
      let: "$a1" := (let: "$a0" := (![go.string] "cmd") in
      (FuncResolve normalizeStatement [] #()) "$a0") in
      (FuncResolve go.append [go.SliceType go.string] #()) "$a0" "$a1") in
      do:  ("out" <-[go.SliceType go.string] "$r0")));;;
    return: (![go.SliceType go.string] "out")).

(* go: normalize.go:14:6 *)
Definition normalizeStatementⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "stmt",
    exception_do (let: "stmt" := (GoAlloc go.string "stmt") in
    let: "out" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$range" := (let: "$a0" := (![go.string] "stmt") in
    (FuncResolve splitSemicolon [] #()) "$a0") in
    (let: "part" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("part" <-[go.string] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![go.string] "part") in
      (FuncResolve strings.TrimSpace [] #()) "$a0") in
      do:  ("part" <-[go.string] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.string] "part") ≠⟨go.string⟩ #""%go)
      then
        let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "out") in
        let: "$a1" := ((let: "$sl0" := (![go.string] "part") in
        CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$sl0")]))) in
        (FuncResolve go.append [go.SliceType go.string] #()) "$a0" "$a1") in
        do:  ("out" <-[go.SliceType go.string] "$r0")
      else do:  #())));;;
    return: (![go.SliceType go.string] "out")).

(* go: normalize.go:25:6 *)
Definition splitSemicolonⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "s",
    exception_do (let: "s" := (GoAlloc go.string "s") in
    return: (let: "$a0" := (![go.string] "s") in
     let: "$a1" := #";"%go in
     (FuncResolve strings.Split [] #()) "$a0" "$a1")).

(* testNormalizeIdempotent checks NormalizeCommands is idempotent (Goose semantics test).

   go: semantics.go:6:6 *)
Definition testNormalizeIdempotentⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "in" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$v0" := #"CREATE USER; GRANT x;"%go in
    let: "$v1" := #";;  DROP;"%go in
    CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0"); KeyedElement None (ElementExpression go.string "$v1")])) in
    do:  ("in" <-[go.SliceType go.string] "$r0");;;
    let: "n1" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "in") in
    (FuncResolve NormalizeCommands [] #()) "$a0") in
    do:  ("n1" <-[go.SliceType go.string] "$r0");;;
    let: "n2" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "n1") in
    (FuncResolve NormalizeCommands [] #()) "$a0") in
    do:  ("n2" <-[go.SliceType go.string] "$r0");;;
    return: (let: "$a0" := (![go.SliceType go.string] "n1") in
     let: "$a1" := (![go.SliceType go.string] "n2") in
     (FuncResolve slices.Equal [go.SliceType go.string; go.string] #()) "$a0" "$a1")).

(* testNormalizeIdempotentEmpty checks idempotence on an empty input slice.

   go: semantics.go:14:6 *)
Definition testNormalizeIdempotentEmptyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "once" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (Convert go.untyped_nil (go.SliceType go.string) UntypedNil) in
    (FuncResolve NormalizeCommands [] #()) "$a0") in
    do:  ("once" <-[go.SliceType go.string] "$r0");;;
    return: (let: "$a0" := (let: "$a0" := (![go.SliceType go.string] "once") in
     (FuncResolve NormalizeCommands [] #()) "$a0") in
     let: "$a1" := (![go.SliceType go.string] "once") in
     (FuncResolve slices.Equal [go.SliceType go.string; go.string] #()) "$a0" "$a1")).

#[global] Instance info' : PkgInfo pkg_id.stmt :=
{|
  pkg_imported_pkgs := [code.strings.pkg_id.strings; code.slices.pkg_id.slices]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.stmt (λ: <>,
      exception_do (do:  (slices.initialize' #());;;
      do:  (strings.initialize' #()))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] NormalizeCommands_unfold :: FuncUnfold NormalizeCommands [] (NormalizeCommandsⁱᵐᵖˡ);
  #[global] normalizeStatement_unfold :: FuncUnfold normalizeStatement [] (normalizeStatementⁱᵐᵖˡ);
  #[global] splitSemicolon_unfold :: FuncUnfold splitSemicolon [] (splitSemicolonⁱᵐᵖˡ);
  #[global] testNormalizeIdempotent_unfold :: FuncUnfold testNormalizeIdempotent [] (testNormalizeIdempotentⁱᵐᵖˡ);
  #[global] testNormalizeIdempotentEmpty_unfold :: FuncUnfold testNormalizeIdempotentEmpty [] (testNormalizeIdempotentEmptyⁱᵐᵖˡ);
  #[global] import_strings_Assumption :: strings.Assumptions;
  #[global] import_slices_Assumption :: slices.Assumptions;
}.
End stmt.
