(* autogenerated from vault-plugin-database-clickhouse/internal/stmts *)
From New.golang Require Import defn.
Module pkg_id.
Definition stmts : go_string := "vault-plugin-database-clickhouse/internal/stmts".

End pkg_id.
Export pkg_id.
Module stmts.

Definition StatementsOrDefault {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmts.StatementsOrDefault"%go.

Definition testStatementsOrDefaultFallback {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmts.testStatementsOrDefaultFallback"%go.

Definition testStatementsOrDefaultProvided {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/stmts.testStatementsOrDefaultProvided"%go.

(* StatementsOrDefault returns provided when non-empty, otherwise a single fallback statement.

   go: ordefault.go:4:6 *)
Definition StatementsOrDefaultⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "provided" "fallback",
    exception_do (let: "fallback" := (GoAlloc go.string "fallback") in
    let: "provided" := (GoAlloc (go.SliceType go.string) "provided") in
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "provided") in
    (FuncResolve go.len [go.SliceType go.string] #()) "$a0") >⟨go.int⟩ #(W64 0))
    then return: (![go.SliceType go.string] "provided")
    else do:  #());;;
    return: (let: "$v0" := (![go.string] "fallback") in
     CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0")]))).

(* testStatementsOrDefaultFallback uses fallback when provided is empty.

   go: semantics.go:4:6 *)
Definition testStatementsOrDefaultFallbackⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "got" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (Convert go.untyped_nil (go.SliceType go.string) UntypedNil) in
    let: "$a1" := #"ALTER USER"%go in
    (FuncResolve StatementsOrDefault [] #()) "$a0" "$a1") in
    do:  ("got" <-[go.SliceType go.string] "$r0");;;
    return: (((let: "$a0" := (![go.SliceType go.string] "got") in
     (FuncResolve go.len [go.SliceType go.string] #()) "$a0") =⟨go.int⟩ #(W64 1)) && ((![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "got", #(W64 0)))) =⟨go.string⟩ #"ALTER USER"%go))).

(* testStatementsOrDefaultProvided keeps non-empty provided statements.

   go: semantics.go:10:6 *)
Definition testStatementsOrDefaultProvidedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "in" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$v0" := #"CREATE USER"%go in
    let: "$v1" := #"GRANT"%go in
    CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0"); KeyedElement None (ElementExpression go.string "$v1")])) in
    do:  ("in" <-[go.SliceType go.string] "$r0");;;
    let: "got" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "in") in
    let: "$a1" := #"ALTER USER"%go in
    (FuncResolve StatementsOrDefault [] #()) "$a0" "$a1") in
    do:  ("got" <-[go.SliceType go.string] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.string] "got") in
    (FuncResolve go.len [go.SliceType go.string] #()) "$a0") ≠⟨go.int⟩ (let: "$a0" := (![go.SliceType go.string] "in") in
    (FuncResolve go.len [go.SliceType go.string] #()) "$a0"))
    then return: (#false)
    else do:  #());;;
    let: "$range" := (![go.SliceType go.string] "in") in
    (let: "i" := (GoAlloc go.int (GoZeroVal go.int #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("i" <-[go.int] "$key");;;
      (if: Convert go.untyped_bool go.bool ((![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "got", ![go.int] "i"))) ≠⟨go.string⟩ (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "in", ![go.int] "i"))))
      then return: (#false)
      else do:  #())));;;
    return: (#true)).

#[global] Instance info' : PkgInfo pkg_id.stmts :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.stmts (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] StatementsOrDefault_unfold :: FuncUnfold StatementsOrDefault [] (StatementsOrDefaultⁱᵐᵖˡ);
  #[global] testStatementsOrDefaultFallback_unfold :: FuncUnfold testStatementsOrDefaultFallback [] (testStatementsOrDefaultFallbackⁱᵐᵖˡ);
  #[global] testStatementsOrDefaultProvided_unfold :: FuncUnfold testStatementsOrDefaultProvided [] (testStatementsOrDefaultProvidedⁱᵐᵖˡ);
}.
End stmts.
