(* autogenerated from vault-plugin-database-clickhouse/internal/txexec *)
Require Export New.code.context.
Require Export New.code.database.sql.
Require Export New.code.fmt.
Require Export New.code.github_com.hashicorp.vault.sdk.helper.dbtxn.
Require Export New.code.vault_plugin_database_clickhouse.internal.stmt.
Require Export New.code.errors.
From New.golang Require Import defn.
Module pkg_id.
Definition txexec : go_string := "vault-plugin-database-clickhouse/internal/txexec".

End pkg_id.
Export pkg_id.
Module txexec.

Definition errStop {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/txexec.errStop"%go.

Definition Execute {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/txexec.Execute"%go.

Definition FirstError {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/txexec.FirstError"%go.

Definition testFirstErrorStops {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/txexec.testFirstErrorStops"%go.

Definition testFirstErrorAllSuccess {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/txexec.testFirstErrorAllSuccess"%go.

Definition testFirstErrorPreserved {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/txexec.testFirstErrorPreserved"%go.

(* Execute runs normalized DDL statements in order; stops at the first failure.

   go: exec.go:13:6 *)
Definition Executeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "ctx" "tx" "commands" "vars",
    exception_do (let: "vars" := (GoAlloc (go.MapType go.string go.string) "vars") in
    let: "commands" := (GoAlloc (go.SliceType go.string) "commands") in
    let: "tx" := (GoAlloc (go.PointerType sql.Tx) "tx") in
    let: "ctx" := (GoAlloc context.Context "ctx") in
    let: "queries" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "commands") in
    (FuncResolve stmt.NormalizeCommands [] #()) "$a0") in
    do:  ("queries" <-[go.SliceType go.string] "$r0");;;
    return: (let: "$a0" := (![go.SliceType go.string] "queries") in
     let: "$a1" := (λ: "q",
       exception_do (let: "q" := (GoAlloc go.string "q") in
       (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
       let: "$r0" := (let: "$a0" := (![context.Context] "ctx") in
       let: "$a1" := (![go.PointerType sql.Tx] "tx") in
       let: "$a2" := (![go.MapType go.string go.string] "vars") in
       let: "$a3" := (![go.string] "q") in
       (FuncResolve dbtxn.ExecuteTxQueryDirect [] #()) "$a0" "$a1" "$a2" "$a3") in
       do:  ("err" <-[go.error] "$r0");;;
       (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
       then
         return: (let: "$a0" := #"execute query %q: %w"%go in
          let: "$a1" := ((let: "$sl0" := (Convert go.string go.any (![go.string] "q")) in
          let: "$sl1" := (Convert go.error go.any (![go.error] "err")) in
          CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0"); KeyedElement None (ElementExpression go.any "$sl1")]))) in
          (FuncResolve fmt.Errorf [] #()) "$a0" "$a1")
       else do:  #()));;;
       return: (Convert go.untyped_nil go.error UntypedNil))
       ) in
     (FuncResolve FirstError [] #()) "$a0" "$a1")).

(* FirstError runs f on each string in order and returns the first error from f.

   go: firsterror.go:4:6 *)
Definition FirstErrorⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "xs" "f",
    exception_do (let: "f" := (GoAlloc (go.FunctionType (go.Signature [go.string] false [go.error])) "f") in
    let: "xs" := (GoAlloc (go.SliceType go.string) "xs") in
    let: "$range" := (![go.SliceType go.string] "xs") in
    (let: "x" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("x" <-[go.string] "$value");;;
      do:  "$key";;;
      (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
      let: "$r0" := (let: "$a0" := (![go.string] "x") in
      (![go.FunctionType (go.Signature [go.string] false [go.error])] "f") "$a0") in
      do:  ("err" <-[go.error] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.error] "err") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))
      then return: (![go.error] "err")
      else do:  #()))));;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* testFirstErrorStops reports execution stops at the first failing step.

   go: semantics.go:8:6 *)
Definition testFirstErrorStopsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "calls" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := #(W64 0) in
    do:  ("calls" <-[go.int] "$r0");;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "$r0" := (let: "$a0" := (let: "$v0" := #"a"%go in
    let: "$v1" := #"b"%go in
    let: "$v2" := #"c"%go in
    CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0"); KeyedElement None (ElementExpression go.string "$v1"); KeyedElement None (ElementExpression go.string "$v2")])) in
    let: "$a1" := (λ: "s",
      exception_do (let: "s" := (GoAlloc go.string "s") in
      do:  ("calls" <-[go.int] ((![go.int] "calls") +⟨go.int⟩ #(W64 1)));;;
      (if: Convert go.untyped_bool go.bool ((![go.string] "s") =⟨go.string⟩ #"b"%go)
      then return: (![go.error] (GlobalVarAddr errStop #()))
      else do:  #());;;
      return: (Convert go.untyped_nil go.error UntypedNil))
      ) in
    (FuncResolve FirstError [] #()) "$a0" "$a1") in
    do:  ("err" <-[go.error] "$r0");;;
    return: (((![go.error] "err") =⟨go.error⟩ (![go.error] (GlobalVarAddr errStop #()))) && ((![go.int] "calls") =⟨go.int⟩ #(W64 2)))).

(* testFirstErrorAllSuccess reports nil when every step succeeds.

   go: semantics.go:21:6 *)
Definition testFirstErrorAllSuccessⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "$r0" := (let: "$a0" := (let: "$v0" := #"a"%go in
    let: "$v1" := #"b"%go in
    let: "$v2" := #"c"%go in
    CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0"); KeyedElement None (ElementExpression go.string "$v1"); KeyedElement None (ElementExpression go.string "$v2")])) in
    let: "$a1" := (λ: <>,
      exception_do (return: (Convert go.untyped_nil go.error UntypedNil))
      ) in
    (FuncResolve FirstError [] #()) "$a0" "$a1") in
    do:  ("err" <-[go.error] "$r0");;;
    return: ((![go.error] "err") =⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

(* testFirstErrorPreserved reports the first error is returned unchanged.

   go: semantics.go:27:6 *)
Definition testFirstErrorPreservedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "want" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "$r0" := (let: "$a0" := #"boom"%go in
    (FuncResolve errors.New [] #()) "$a0") in
    do:  ("want" <-[go.error] "$r0");;;
    let: "err" := (GoAlloc go.error (GoZeroVal go.error #())) in
    let: "$r0" := (let: "$a0" := (let: "$v0" := #"1"%go in
    let: "$v1" := #"2"%go in
    let: "$v2" := #"3"%go in
    CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$v0"); KeyedElement None (ElementExpression go.string "$v1"); KeyedElement None (ElementExpression go.string "$v2")])) in
    let: "$a1" := (λ: "s",
      exception_do (let: "s" := (GoAlloc go.string "s") in
      (if: Convert go.untyped_bool go.bool ((![go.string] "s") =⟨go.string⟩ #"1"%go)
      then return: (![go.error] "want")
      else do:  #());;;
      return: (let: "$a0" := #"later"%go in
       (FuncResolve errors.New [] #()) "$a0"))
      ) in
    (FuncResolve FirstError [] #()) "$a0" "$a1") in
    do:  ("err" <-[go.error] "$r0");;;
    return: ((![go.error] "err") =⟨go.error⟩ (![go.error] "want"))).

#[global] Instance info' : PkgInfo pkg_id.txexec :=
{|
  pkg_imported_pkgs := [code.context.pkg_id.context; code.database.sql.pkg_id.sql; code.fmt.pkg_id.fmt; code.github_com.hashicorp.vault.sdk.helper.dbtxn.pkg_id.dbtxn; code.vault_plugin_database_clickhouse.internal.stmt.pkg_id.stmt; code.errors.pkg_id.errors]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.txexec (λ: <>,
      exception_do (do:  (go.GlobalAlloc errStop go.error #());;;
      do:  (errors.initialize' #());;;
      do:  (stmt.initialize' #());;;
      do:  (dbtxn.initialize' #());;;
      do:  (fmt.initialize' #());;;
      do:  (sql.initialize' #());;;
      do:  (context.initialize' #());;;
      let: "$r0" := (let: "$a0" := #"stop"%go in
      (FuncResolve errors.New [] #()) "$a0") in
      do:  ((GlobalVarAddr errStop #()) <-[go.error] "$r0"))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Execute_unfold :: FuncUnfold Execute [] (Executeⁱᵐᵖˡ);
  #[global] FirstError_unfold :: FuncUnfold FirstError [] (FirstErrorⁱᵐᵖˡ);
  #[global] testFirstErrorStops_unfold :: FuncUnfold testFirstErrorStops [] (testFirstErrorStopsⁱᵐᵖˡ);
  #[global] testFirstErrorAllSuccess_unfold :: FuncUnfold testFirstErrorAllSuccess [] (testFirstErrorAllSuccessⁱᵐᵖˡ);
  #[global] testFirstErrorPreserved_unfold :: FuncUnfold testFirstErrorPreserved [] (testFirstErrorPreservedⁱᵐᵖˡ);
  #[global] import_context_Assumption :: context.Assumptions;
  #[global] import_sql_Assumption :: sql.Assumptions;
  #[global] import_fmt_Assumption :: fmt.Assumptions;
  #[global] import_dbtxn_Assumption :: dbtxn.Assumptions;
  #[global] import_stmt_Assumption :: stmt.Assumptions;
  #[global] import_errors_Assumption :: errors.Assumptions;
}.
End txexec.
