(* autogenerated from vault-plugin-database-clickhouse/internal/validate *)
Require Export New.code.fmt.
From New.golang Require Import defn.
Module pkg_id.
Definition validate : go_string := "vault-plugin-database-clickhouse/internal/validate".

End pkg_id.
Export pkg_id.
Module validate.

Definition testUpdateUserValid {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/validate.testUpdateUserValid"%go.

Definition testUpdateUserMissingUsername {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/validate.testUpdateUserMissingUsername"%go.

Definition testCreationStatementsRequiresOne {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/validate.testCreationStatementsRequiresOne"%go.

Definition UpdateUser {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/validate.UpdateUser"%go.

Definition CreationStatements {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/validate.CreationStatements"%go.

(* testUpdateUserValid accepts username with a password change.

   go: semantics.go:4:6 *)
Definition testUpdateUserValidⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := #"alice"%go in
     let: "$a1" := #true in
     let: "$a2" := #false in
     (FuncResolve UpdateUser [] #()) "$a0" "$a1" "$a2") =⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

(* testUpdateUserMissingUsername rejects empty username.

   go: semantics.go:9:6 *)
Definition testUpdateUserMissingUsernameⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := #""%go in
     let: "$a1" := #true in
     let: "$a2" := #false in
     (FuncResolve UpdateUser [] #()) "$a0" "$a1" "$a2") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

(* testCreationStatementsRequiresOne rejects empty creation lists.

   go: semantics.go:14:6 *)
Definition testCreationStatementsRequiresOneⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: ((let: "$a0" := #(W64 0) in
     (FuncResolve CreationStatements [] #()) "$a0") ≠⟨go.error⟩ (Convert go.untyped_nil go.error UntypedNil))).

(* UpdateUser checks UpdateUser request fields.

   go: update.go:6:6 *)
Definition UpdateUserⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "username" "hasPassword" "hasExpiration",
    exception_do (let: "hasExpiration" := (GoAlloc go.bool "hasExpiration") in
    let: "hasPassword" := (GoAlloc go.bool "hasPassword") in
    let: "username" := (GoAlloc go.string "username") in
    (if: Convert go.untyped_bool go.bool ((![go.string] "username") =⟨go.string⟩ #""%go)
    then
      return: (let: "$a0" := #"missing username"%go in
       let: "$a1" := #slice.nil in
       (FuncResolve fmt.Errorf [] #()) "$a0" "$a1")
    else do:  #());;;
    (if: (⟨go.bool⟩! (![go.bool] "hasPassword")) && (⟨go.bool⟩! (![go.bool] "hasExpiration"))
    then
      return: (let: "$a0" := #"no changes requested"%go in
       let: "$a1" := #slice.nil in
       (FuncResolve fmt.Errorf [] #()) "$a0" "$a1")
    else do:  #());;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* CreationStatements checks NewUser has at least one creation statement.

   go: update.go:17:6 *)
Definition CreationStatementsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "count",
    exception_do (let: "count" := (GoAlloc go.int "count") in
    (if: Convert go.untyped_bool go.bool ((![go.int] "count") ≤⟨go.int⟩ #(W64 0))
    then
      return: (let: "$a0" := #"empty creation statements"%go in
       let: "$a1" := #slice.nil in
       (FuncResolve fmt.Errorf [] #()) "$a0" "$a1")
    else do:  #());;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

#[global] Instance info' : PkgInfo pkg_id.validate :=
{|
  pkg_imported_pkgs := [code.fmt.pkg_id.fmt]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.validate (λ: <>,
      exception_do (do:  (fmt.initialize' #()))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] testUpdateUserValid_unfold :: FuncUnfold testUpdateUserValid [] (testUpdateUserValidⁱᵐᵖˡ);
  #[global] testUpdateUserMissingUsername_unfold :: FuncUnfold testUpdateUserMissingUsername [] (testUpdateUserMissingUsernameⁱᵐᵖˡ);
  #[global] testCreationStatementsRequiresOne_unfold :: FuncUnfold testCreationStatementsRequiresOne [] (testCreationStatementsRequiresOneⁱᵐᵖˡ);
  #[global] UpdateUser_unfold :: FuncUnfold UpdateUser [] (UpdateUserⁱᵐᵖˡ);
  #[global] CreationStatements_unfold :: FuncUnfold CreationStatements [] (CreationStatementsⁱᵐᵖˡ);
  #[global] import_fmt_Assumption :: fmt.Assumptions;
}.
End validate.
