(* autogenerated from vault-plugin-database-clickhouse/internal/vars *)
Require Export New.code.maps.
From New.golang Require Import defn.
Module pkg_id.
Definition vars : go_string := "vault-plugin-database-clickhouse/internal/vars".

End pkg_id.
Export pkg_id.
Module vars.

Definition Operation {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "vault-plugin-database-clickhouse/internal/vars.Operation"%go [].

#[global] Opaque Operation.

Definition TemplateVars {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "vault-plugin-database-clickhouse/internal/vars.TemplateVars"%go [].

#[global] Opaque TemplateVars.

Definition OpNewUser {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 0).

Definition OpUpdatePassword {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 1).

Definition OpUpdateExpiration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 2).

Definition OpDeleteUser {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 3).

Definition requiredByOp {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.requiredByOp"%go.

Definition New {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.New"%go.

Definition RequiredKeys {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.RequiredKeys"%go.

Definition HasRequiredKeys {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.HasRequiredKeys"%go.

Definition ForNewUser {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.ForNewUser"%go.

Definition ForUpdatePassword {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.ForUpdatePassword"%go.

Definition ForUpdateExpiration {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.ForUpdateExpiration"%go.

Definition ForDeleteUser {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.ForDeleteUser"%go.

Definition testNewUserHasRequiredKeys {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.testNewUserHasRequiredKeys"%go.

Definition testAllOpsHaveRequiredKeys {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/vars.testAllOpsHaveRequiredKeys"%go.

(* New copies base into a TemplateVars value.

   go: builder.go:25:6 *)
Definition Newⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "base",
    exception_do (let: "base" := (GoAlloc (go.MapType go.string go.string) "base") in
    let: "copied" := (GoAlloc (go.MapType go.string go.string) (GoZeroVal (go.MapType go.string go.string) #())) in
    let: "$r0" := ((FuncResolve go.make2 [go.MapType go.string go.string] #()) (let: "$a0" := (![go.MapType go.string go.string] "base") in
    (FuncResolve go.len [go.MapType go.string go.string] #()) "$a0")) in
    do:  ("copied" <-[go.MapType go.string go.string] "$r0");;;
    do:  (let: "$a0" := (![go.MapType go.string go.string] "copied") in
    let: "$a1" := (![go.MapType go.string go.string] "base") in
    (FuncResolve maps.Copy [go.MapType go.string go.string; go.MapType go.string go.string; go.string; go.string] #()) "$a0" "$a1");;;
    return: (let: "$v0" := (![go.MapType go.string go.string] "copied") in
     CompositeLiteral TemplateVars (LiteralValue [KeyedElement (Some (KeyField "values"%go)) (ElementExpression (go.MapType go.string go.string) "$v0")]))).

(* go: builder.go:31:23 *)
Definition TemplateVars__Mapⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "v" <>,
    exception_do (let: "v" := (GoAlloc TemplateVars "v") in
    let: "out" := (GoAlloc (go.MapType go.string go.string) (GoZeroVal (go.MapType go.string go.string) #())) in
    let: "$r0" := ((FuncResolve go.make2 [go.MapType go.string go.string] #()) (let: "$a0" := (![go.MapType go.string go.string] (StructFieldRef TemplateVars "values"%go "v")) in
    (FuncResolve go.len [go.MapType go.string go.string] #()) "$a0")) in
    do:  ("out" <-[go.MapType go.string go.string] "$r0");;;
    do:  (let: "$a0" := (![go.MapType go.string go.string] "out") in
    let: "$a1" := (![go.MapType go.string go.string] (StructFieldRef TemplateVars "values"%go "v")) in
    (FuncResolve maps.Copy [go.MapType go.string go.string; go.MapType go.string go.string; go.string; go.string] #()) "$a0" "$a1");;;
    return: (![go.MapType go.string go.string] "out")).

(* go: builder.go:37:23 *)
Definition TemplateVars__Keysⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "v" <>,
    exception_do (let: "v" := (GoAlloc TemplateVars "v") in
    let: "out" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := ((FuncResolve go.make3 [go.SliceType go.string] #()) #(W64 0) (let: "$a0" := (![go.MapType go.string go.string] (StructFieldRef TemplateVars "values"%go "v")) in
    (FuncResolve go.len [go.MapType go.string go.string] #()) "$a0")) in
    do:  ("out" <-[go.SliceType go.string] "$r0");;;
    let: "$range" := (![go.MapType go.string go.string] (StructFieldRef TemplateVars "values"%go "v")) in
    (let: "k" := (GoAlloc go.string (GoZeroVal go.string #())) in
    map.for_range go.string go.string "$range" (λ: "$key" "$value",
      do:  ("k" <-[go.string] "$key");;;
      let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "out") in
      let: "$a1" := ((let: "$sl0" := (![go.string] "k") in
      CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$sl0")]))) in
      (FuncResolve go.append [go.SliceType go.string] #()) "$a0" "$a1") in
      do:  ("out" <-[go.SliceType go.string] "$r0")));;;
    return: (![go.SliceType go.string] "out")).

(* go: builder.go:45:23 *)
Definition TemplateVars__Hasⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "v" "key",
    exception_do (let: "v" := (GoAlloc TemplateVars "v") in
    let: "key" := (GoAlloc go.string "key") in
    let: "ok" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: ("$ret0", "$ret1") := (map.lookup2 go.string go.string (![go.MapType go.string go.string] (StructFieldRef TemplateVars "values"%go "v")) (![go.string] "key")) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  "$r0";;;
    do:  ("ok" <-[go.bool] "$r1");;;
    return: (![go.bool] "ok")).

(* RequiredKeys lists template placeholders used by default statements for op.

   go: builder.go:58:6 *)
Definition RequiredKeysⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "op",
    exception_do (let: "op" := (GoAlloc Operation "op") in
    return: (map.lookup1 Operation (go.SliceType go.string) (![go.MapType Operation (go.SliceType go.string)] (GlobalVarAddr requiredByOp #())) (![Operation] "op"))).

(* HasRequiredKeys reports whether v contains every key RequiredKeys lists for op.

   go: builder.go:63:6 *)
Definition HasRequiredKeysⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "op" "v",
    exception_do (let: "v" := (GoAlloc TemplateVars "v") in
    let: "op" := (GoAlloc Operation "op") in
    let: "$range" := (let: "$a0" := (![Operation] "op") in
    (FuncResolve RequiredKeys [] #()) "$a0") in
    (let: "k" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("k" <-[go.string] "$value");;;
      do:  "$key";;;
      (if: (⟨go.bool⟩! (let: "$a0" := (![go.string] "k") in
      (MethodResolve (go.PointerType TemplateVars) "Has"%go "v") "$a0"))
      then return: (#false)
      else do:  #())));;;
    return: (#true)).

(* go: builder.go:72:6 *)
Definition ForNewUserⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "username" "password" "expiration" "cluster",
    exception_do (let: "cluster" := (GoAlloc go.string "cluster") in
    let: "expiration" := (GoAlloc go.string "expiration") in
    let: "password" := (GoAlloc go.string "password") in
    let: "username" := (GoAlloc go.string "username") in
    return: (let: "$a0" := (let: "$k0" := #"name"%go in
     let: "$v1" := (![go.string] "username") in
     let: "$k2" := #"username"%go in
     let: "$v3" := (![go.string] "username") in
     let: "$k4" := #"password"%go in
     let: "$v5" := (![go.string] "password") in
     let: "$k6" := #"expiration"%go in
     let: "$v7" := (![go.string] "expiration") in
     let: "$k8" := #"cluster"%go in
     let: "$v9" := (![go.string] "cluster") in
     CompositeLiteral (go.MapType go.string go.string) (LiteralValue [KeyedElement (Some (KeyExpression go.string "$k0")) (ElementExpression go.string "$v1"); KeyedElement (Some (KeyExpression go.string "$k2")) (ElementExpression go.string "$v3"); KeyedElement (Some (KeyExpression go.string "$k4")) (ElementExpression go.string "$v5"); KeyedElement (Some (KeyExpression go.string "$k6")) (ElementExpression go.string "$v7"); KeyedElement (Some (KeyExpression go.string "$k8")) (ElementExpression go.string "$v9")])) in
     (FuncResolve New [] #()) "$a0")).

(* go: builder.go:82:6 *)
Definition ForUpdatePasswordⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "username" "password" "cluster",
    exception_do (let: "cluster" := (GoAlloc go.string "cluster") in
    let: "password" := (GoAlloc go.string "password") in
    let: "username" := (GoAlloc go.string "username") in
    return: (let: "$a0" := (let: "$k0" := #"name"%go in
     let: "$v1" := (![go.string] "username") in
     let: "$k2" := #"username"%go in
     let: "$v3" := (![go.string] "username") in
     let: "$k4" := #"password"%go in
     let: "$v5" := (![go.string] "password") in
     let: "$k6" := #"cluster"%go in
     let: "$v7" := (![go.string] "cluster") in
     CompositeLiteral (go.MapType go.string go.string) (LiteralValue [KeyedElement (Some (KeyExpression go.string "$k0")) (ElementExpression go.string "$v1"); KeyedElement (Some (KeyExpression go.string "$k2")) (ElementExpression go.string "$v3"); KeyedElement (Some (KeyExpression go.string "$k4")) (ElementExpression go.string "$v5"); KeyedElement (Some (KeyExpression go.string "$k6")) (ElementExpression go.string "$v7")])) in
     (FuncResolve New [] #()) "$a0")).

(* go: builder.go:91:6 *)
Definition ForUpdateExpirationⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "username" "expiration" "cluster",
    exception_do (let: "cluster" := (GoAlloc go.string "cluster") in
    let: "expiration" := (GoAlloc go.string "expiration") in
    let: "username" := (GoAlloc go.string "username") in
    return: (let: "$a0" := (let: "$k0" := #"name"%go in
     let: "$v1" := (![go.string] "username") in
     let: "$k2" := #"username"%go in
     let: "$v3" := (![go.string] "username") in
     let: "$k4" := #"expiration"%go in
     let: "$v5" := (![go.string] "expiration") in
     let: "$k6" := #"cluster"%go in
     let: "$v7" := (![go.string] "cluster") in
     CompositeLiteral (go.MapType go.string go.string) (LiteralValue [KeyedElement (Some (KeyExpression go.string "$k0")) (ElementExpression go.string "$v1"); KeyedElement (Some (KeyExpression go.string "$k2")) (ElementExpression go.string "$v3"); KeyedElement (Some (KeyExpression go.string "$k4")) (ElementExpression go.string "$v5"); KeyedElement (Some (KeyExpression go.string "$k6")) (ElementExpression go.string "$v7")])) in
     (FuncResolve New [] #()) "$a0")).

(* go: builder.go:100:6 *)
Definition ForDeleteUserⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "username",
    exception_do (let: "username" := (GoAlloc go.string "username") in
    return: (let: "$a0" := (let: "$k0" := #"name"%go in
     let: "$v1" := (![go.string] "username") in
     let: "$k2" := #"username"%go in
     let: "$v3" := (![go.string] "username") in
     CompositeLiteral (go.MapType go.string go.string) (LiteralValue [KeyedElement (Some (KeyExpression go.string "$k0")) (ElementExpression go.string "$v1"); KeyedElement (Some (KeyExpression go.string "$k2")) (ElementExpression go.string "$v3")])) in
     (FuncResolve New [] #()) "$a0")).

(* testNewUserHasRequiredKeys reports ForNewUser supplies every required placeholder.

   go: semantics.go:4:6 *)
Definition testNewUserHasRequiredKeysⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (let: "v" := (GoAlloc TemplateVars (GoZeroVal TemplateVars #())) in
    let: "$r0" := (let: "$a0" := #"u"%go in
    let: "$a1" := #"p"%go in
    let: "$a2" := #"e"%go in
    let: "$a3" := #"c"%go in
    (FuncResolve ForNewUser [] #()) "$a0" "$a1" "$a2" "$a3") in
    do:  ("v" <-[TemplateVars] "$r0");;;
    return: (let: "$a0" := OpNewUser in
     let: "$a1" := (![TemplateVars] "v") in
     (FuncResolve HasRequiredKeys [] #()) "$a0" "$a1")).

(* testAllOpsHaveRequiredKeys reports each For* builder matches its operation keys.

   go: semantics.go:10:6 *)
Definition testAllOpsHaveRequiredKeysⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do ((if: (⟨go.bool⟩! (let: "$a0" := OpNewUser in
    let: "$a1" := (let: "$a0" := #"u"%go in
    let: "$a1" := #"p"%go in
    let: "$a2" := #"e"%go in
    let: "$a3" := #"c"%go in
    (FuncResolve ForNewUser [] #()) "$a0" "$a1" "$a2" "$a3") in
    (FuncResolve HasRequiredKeys [] #()) "$a0" "$a1"))
    then return: (#false)
    else do:  #());;;
    (if: (⟨go.bool⟩! (let: "$a0" := OpUpdatePassword in
    let: "$a1" := (let: "$a0" := #"u"%go in
    let: "$a1" := #"p"%go in
    let: "$a2" := #"c"%go in
    (FuncResolve ForUpdatePassword [] #()) "$a0" "$a1" "$a2") in
    (FuncResolve HasRequiredKeys [] #()) "$a0" "$a1"))
    then return: (#false)
    else do:  #());;;
    (if: (⟨go.bool⟩! (let: "$a0" := OpUpdateExpiration in
    let: "$a1" := (let: "$a0" := #"u"%go in
    let: "$a1" := #"e"%go in
    let: "$a2" := #"c"%go in
    (FuncResolve ForUpdateExpiration [] #()) "$a0" "$a1" "$a2") in
    (FuncResolve HasRequiredKeys [] #()) "$a0" "$a1"))
    then return: (#false)
    else do:  #());;;
    return: (let: "$a0" := OpDeleteUser in
     let: "$a1" := (let: "$a0" := #"u"%go in
     (FuncResolve ForDeleteUser [] #()) "$a0") in
     (FuncResolve HasRequiredKeys [] #()) "$a0" "$a1")).

#[global] Instance info' : PkgInfo pkg_id.vars :=
{|
  pkg_imported_pkgs := [code.maps.pkg_id.maps]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.vars (λ: <>,
      exception_do (do:  (go.GlobalAlloc requiredByOp (go.MapType Operation (go.SliceType go.string)) #());;;
      do:  (maps.initialize' #());;;
      let: "$r0" := (let: "$k0" := OpNewUser in
      let: "$v1" := #"name"%go in
      let: "$v2" := #"username"%go in
      let: "$v3" := #"password"%go in
      let: "$v4" := #"expiration"%go in
      let: "$v5" := #"cluster"%go in
      let: "$k6" := OpUpdatePassword in
      let: "$v7" := #"name"%go in
      let: "$v8" := #"username"%go in
      let: "$v9" := #"password"%go in
      let: "$v10" := #"cluster"%go in
      let: "$k11" := OpUpdateExpiration in
      let: "$v12" := #"name"%go in
      let: "$v13" := #"username"%go in
      let: "$v14" := #"expiration"%go in
      let: "$v15" := #"cluster"%go in
      let: "$k16" := OpDeleteUser in
      let: "$v17" := #"name"%go in
      let: "$v18" := #"username"%go in
      CompositeLiteral (go.MapType Operation (go.SliceType go.string)) (LiteralValue [KeyedElement (Some (KeyExpression Operation "$k0")) (ElementLiteralValue [KeyedElement None (ElementExpression go.string "$v1"); KeyedElement None (ElementExpression go.string "$v2"); KeyedElement None (ElementExpression go.string "$v3"); KeyedElement None (ElementExpression go.string "$v4"); KeyedElement None (ElementExpression go.string "$v5")]); KeyedElement (Some (KeyExpression Operation "$k6")) (ElementLiteralValue [KeyedElement None (ElementExpression go.string "$v7"); KeyedElement None (ElementExpression go.string "$v8"); KeyedElement None (ElementExpression go.string "$v9"); KeyedElement None (ElementExpression go.string "$v10")]); KeyedElement (Some (KeyExpression Operation "$k11")) (ElementLiteralValue [KeyedElement None (ElementExpression go.string "$v12"); KeyedElement None (ElementExpression go.string "$v13"); KeyedElement None (ElementExpression go.string "$v14"); KeyedElement None (ElementExpression go.string "$v15")]); KeyedElement (Some (KeyExpression Operation "$k16")) (ElementLiteralValue [KeyedElement None (ElementExpression go.string "$v17"); KeyedElement None (ElementExpression go.string "$v18")])])) in
      do:  ((GlobalVarAddr requiredByOp #()) <-[go.MapType Operation (go.SliceType go.string)] "$r0"))
      ).

Module Operation.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Definition t : Type := w64.
#[global] Arguments t : clear implicits.
End def.
End Operation.

Definition Operationⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.int.

Class Operation_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Operation_underlying :: (Operation) <u (Operationⁱᵐᵖˡ);
}.

Module TemplateVars.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  values' : map.t;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End TemplateVars.

Definition TemplateVars'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "values"%go (go.MapType go.string go.string))
].
Program Definition TemplateVars'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (TemplateVars'fds_unsealed).
Global Instance equals_unfold_TemplateVars {ext : ffi_syntax} {go_gctx : GoGlobalContext} : TemplateVars'fds =→ TemplateVars'fds_unsealed.
Proof. rewrite /TemplateVars'fds seal_eq //. Qed.

Definition TemplateVarsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (TemplateVars'fds).

Class TemplateVars_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TemplateVars_type_repr  :: go.TypeReprUnderlying TemplateVarsⁱᵐᵖˡ TemplateVars.t;
  #[global] TemplateVars_underlying :: (TemplateVars) <u (TemplateVarsⁱᵐᵖˡ);
  #[global] TemplateVars_get_values (x : TemplateVars.t) :: ⟦StructFieldGet (TemplateVarsⁱᵐᵖˡ) "values", #x⟧ ⤳[under] #x.(TemplateVars.values');
  #[global] TemplateVars_set_values (x : TemplateVars.t) y :: ⟦StructFieldSet (TemplateVarsⁱᵐᵖˡ) "values", (#x, #y)⟧ ⤳[under] #(x <|TemplateVars.values' := y|>);
  #[global] TemplateVars_Has_unfold :: MethodUnfold (TemplateVars) "Has" (TemplateVars__Hasⁱᵐᵖˡ);
  #[global] TemplateVars_Keys_unfold :: MethodUnfold (TemplateVars) "Keys" (TemplateVars__Keysⁱᵐᵖˡ);
  #[global] TemplateVars_Map_unfold :: MethodUnfold (TemplateVars) "Map" (TemplateVars__Mapⁱᵐᵖˡ);
  #[global] TemplateVars'ptr_Has_unfold :: MethodUnfold (go.PointerType (TemplateVars)) "Has" (λ: "$r", MethodResolve (TemplateVars) "Has" (![(TemplateVars)] "$r"));
  #[global] TemplateVars'ptr_Keys_unfold :: MethodUnfold (go.PointerType (TemplateVars)) "Keys" (λ: "$r", MethodResolve (TemplateVars) "Keys" (![(TemplateVars)] "$r"));
  #[global] TemplateVars'ptr_Map_unfold :: MethodUnfold (go.PointerType (TemplateVars)) "Map" (λ: "$r", MethodResolve (TemplateVars) "Map" (![(TemplateVars)] "$r"));
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Operation_instance :: Operation_Assumptions;
  #[global] TemplateVars_instance :: TemplateVars_Assumptions;
  #[global] New_unfold :: FuncUnfold New [] (Newⁱᵐᵖˡ);
  #[global] RequiredKeys_unfold :: FuncUnfold RequiredKeys [] (RequiredKeysⁱᵐᵖˡ);
  #[global] HasRequiredKeys_unfold :: FuncUnfold HasRequiredKeys [] (HasRequiredKeysⁱᵐᵖˡ);
  #[global] ForNewUser_unfold :: FuncUnfold ForNewUser [] (ForNewUserⁱᵐᵖˡ);
  #[global] ForUpdatePassword_unfold :: FuncUnfold ForUpdatePassword [] (ForUpdatePasswordⁱᵐᵖˡ);
  #[global] ForUpdateExpiration_unfold :: FuncUnfold ForUpdateExpiration [] (ForUpdateExpirationⁱᵐᵖˡ);
  #[global] ForDeleteUser_unfold :: FuncUnfold ForDeleteUser [] (ForDeleteUserⁱᵐᵖˡ);
  #[global] testNewUserHasRequiredKeys_unfold :: FuncUnfold testNewUserHasRequiredKeys [] (testNewUserHasRequiredKeysⁱᵐᵖˡ);
  #[global] testAllOpsHaveRequiredKeys_unfold :: FuncUnfold testAllOpsHaveRequiredKeys [] (testAllOpsHaveRequiredKeysⁱᵐᵖˡ);
  #[global] import_maps_Assumption :: maps.Assumptions;
}.
End vars.
