(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.vault_plugin_database_clickhouse.internal.firsterror.

Set Default Proof Using "Type".

Module firsterror.
End firsterror.
