(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.slices.
Require Export New.generatedproof.strings.
Require Export New.golang.theory.
Require Export New.code.vault_plugin_database_clickhouse.internal.stmt.

Set Default Proof Using "Type".

Module stmt.
End stmt.
