(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.context.
Require Export New.generatedproof.database.sql.
Require Export New.generatedproof.errors.
Require Export New.generatedproof.fmt.
Require Export New.generatedproof.github_com.hashicorp.vault.sdk.helper.dbtxn.
Require Export New.generatedproof.vault_plugin_database_clickhouse.internal.stmt.
Require Export New.golang.theory.
Require Export New.code.vault_plugin_database_clickhouse.internal.txexec.

Set Default Proof Using "Type".

Module txexec.
End txexec.
