(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.maps.
Require Export New.golang.theory.
Require Export New.code.vault_plugin_database_clickhouse.internal.vars.

Set Default Proof Using "Type".

Module vars.
Module TemplateVars.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : vars.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance TemplateVars_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (vars.TemplateVars.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "values" ∷ l.[(vars.TemplateVars.t), "values"] ↦{dq} v.(vars.TemplateVars.values') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance TemplateVars_into_val_typed
   :
  IntoValTypedUnderlying (vars.TemplateVars.t) (vars.TemplateVarsⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance TemplateVars_access_load_values l (v : (vars.TemplateVars.t)) dq :
  AccessStrict
    (l.[(vars.TemplateVars.t), "values"] ↦{dq} (v.(vars.TemplateVars.values')))
    (l.[(vars.TemplateVars.t), "values"] ↦{dq} (v.(vars.TemplateVars.values')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance TemplateVars_access_store_values l (v : (vars.TemplateVars.t)) values' :
  AccessStrict
    (l.[(vars.TemplateVars.t), "values"] ↦ (v.(vars.TemplateVars.values')))
    (l.[(vars.TemplateVars.t), "values"] ↦ values')
    (l ↦ v) (l ↦ (v <|(vars.TemplateVars.values') := values'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End TemplateVars.

End vars.
