(* autogenerated from vault-plugin-database-clickhouse/internal/cluster/choose *)
Require Export New.code.sort.
Require Export New.code.strings.
Require Export New.code.errors.
From New.golang Require Import defn.
Module pkg_id.
Definition choose : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose".

End pkg_id.
Export pkg_id.
Module choose.

Definition ErrEmptyCluster {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.ErrEmptyCluster"%go.

Definition ErrAmbiguousCluster {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.ErrAmbiguousCluster"%go.

Definition ChooseCluster {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.ChooseCluster"%go.

Definition distinctNonEmpty {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.distinctNonEmpty"%go.

Definition configuredWins {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.configuredWins"%go.

Definition discoveryRequired {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.discoveryRequired"%go.

Definition testChooseConfigured {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.testChooseConfigured"%go.

Definition testChooseSingleDiscovery {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.testChooseSingleDiscovery"%go.

Definition testChooseEmptyError {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.testChooseEmptyError"%go.

Definition testChooseAmbiguous {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "vault-plugin-database-clickhouse/internal/cluster/choose.testChooseAmbiguous"%go.

(* ChooseCluster returns configured when set, the sole discovered name, or an error.

   go: choose.go:9:6 *)
Definition ChooseClusterⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "configured" "discovered",
    exception_do (let: "discovered" := (GoAlloc (go.SliceType go.string) "discovered") in
    let: "configured" := (GoAlloc go.string "configured") in
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.string] "configured") in
    (FuncResolve strings.TrimSpace [] #()) "$a0") ≠⟨go.string⟩ #""%go)
    then return: (![go.string] "configured", Convert go.untyped_nil go.error UntypedNil)
    else do:  #());;;
    let: "names" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "discovered") in
    (FuncResolve distinctNonEmpty [] #()) "$a0") in
    do:  ("names" <-[go.SliceType go.string] "$r0");;;
    let: "$sw" := (let: "$a0" := (![go.SliceType go.string] "names") in
    (FuncResolve go.len [go.SliceType go.string] #()) "$a0") in
    (if: "$sw" =⟨go.int⟩ #(W64 0)
    then return: (#""%go, ![go.error] (GlobalVarAddr ErrEmptyCluster #()))
    else
      (if: "$sw" =⟨go.int⟩ #(W64 1)
      then return: (![go.string] (IndexRef (go.SliceType go.string) (![go.SliceType go.string] "names", #(W64 0))), Convert go.untyped_nil go.error UntypedNil)
      else return: (#""%go, ![go.error] (GlobalVarAddr ErrAmbiguousCluster #()))))).

(* go: choose.go:24:6 *)
Definition distinctNonEmptyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "names",
    exception_do (let: "names" := (GoAlloc (go.SliceType go.string) "names") in
    let: "seen" := (GoAlloc (go.MapType go.string (go.StructType [

    ])) (GoZeroVal (go.MapType go.string (go.StructType [

    ])) #())) in
    let: "$r0" := ((FuncResolve go.make1 [go.MapType go.string (go.StructType [

     ])] #()) #()) in
    do:  ("seen" <-[go.MapType go.string (go.StructType [

    ])] "$r0");;;
    let: "out" := (GoAlloc (go.SliceType go.string) (GoZeroVal (go.SliceType go.string) #())) in
    let: "$range" := (![go.SliceType go.string] "names") in
    (let: "name" := (GoAlloc go.string (GoZeroVal go.string #())) in
    slice.for_range go.string "$range" (λ: "$key" "$value",
      do:  ("name" <-[go.string] "$value");;;
      do:  "$key";;;
      let: "$r0" := (let: "$a0" := (![go.string] "name") in
      (FuncResolve strings.TrimSpace [] #()) "$a0") in
      do:  ("name" <-[go.string] "$r0");;;
      (if: Convert go.untyped_bool go.bool ((![go.string] "name") =⟨go.string⟩ #""%go)
      then continue: #()
      else do:  #());;;
      (let: "ok" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
      let: ("$ret0", "$ret1") := (map.lookup2 go.string (go.StructType [

      ]) (![go.MapType go.string (go.StructType [

      ])] "seen") (![go.string] "name")) in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      do:  "$r0";;;
      do:  ("ok" <-[go.bool] "$r1");;;
      (if: ![go.bool] "ok"
      then continue: #()
      else do:  #()));;;
      let: "$r0" := (CompositeLiteral (go.StructType [

      ]) (LiteralValue [])) in
      do:  (map.insert go.string (![go.MapType go.string (go.StructType [

      ])] "seen") (![go.string] "name") "$r0");;;
      let: "$r0" := (let: "$a0" := (![go.SliceType go.string] "out") in
      let: "$a1" := ((let: "$sl0" := (![go.string] "name") in
      CompositeLiteral (go.SliceType go.string) (LiteralValue [KeyedElement None (ElementExpression go.string "$sl0")]))) in
      (FuncResolve go.append [go.SliceType go.string] #()) "$a0" "$a1") in
      do:  ("out" <-[go.SliceType go.string] "$r0")));;;
    do:  (let: "$a0" := (![go.SliceType go.string] "out") in
    (FuncResolve sort.Strings [] #()) "$a0");;;
    return: (![go.SliceType go.string] "out")).

(* go: semantics.go:3:6 *)
Definition configuredWinsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "configured",
    exception_do (let: "configured" := (GoAlloc go.string "configured") in
    return: ((![go.string] "configured") ≠⟨go.string⟩ #""%go)).

(* go: semantics.go:5:6 *)
Definition discoveryRequiredⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "configured",
    exception_do (let: "configured" := (GoAlloc go.string "configured") in
    return: ((![go.string] "configured") =⟨go.string⟩ #""%go)).

(* testChooseConfigured reports a non-empty configured name wins.

   go: semantics.go:8:6 *)
Definition testChooseConfiguredⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (let: "$a0" := #"cfg"%go in
     (FuncResolve configuredWins [] #()) "$a0")).

(* testChooseSingleDiscovery reports configured name is returned when set.

   go: semantics.go:13:6 *)
Definition testChooseSingleDiscoveryⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (let: "$a0" := #"default"%go in
     (FuncResolve configuredWins [] #()) "$a0")).

(* testChooseEmptyError reports empty configured requires discovery.

   go: semantics.go:18:6 *)
Definition testChooseEmptyErrorⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (let: "$a0" := #""%go in
     (FuncResolve discoveryRequired [] #()) "$a0")).

(* testChooseAmbiguous reports empty configured requires discovery.

   go: semantics.go:23:6 *)
Definition testChooseAmbiguousⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (let: "$a0" := #""%go in
     (FuncResolve discoveryRequired [] #()) "$a0")).

#[global] Instance info' : PkgInfo pkg_id.choose :=
{|
  pkg_imported_pkgs := [code.sort.pkg_id.sort; code.strings.pkg_id.strings; code.errors.pkg_id.errors]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.choose (λ: <>,
      exception_do (do:  (go.GlobalAlloc ErrAmbiguousCluster go.error #());;;
      do:  (go.GlobalAlloc ErrEmptyCluster go.error #());;;
      do:  (errors.initialize' #());;;
      do:  (strings.initialize' #());;;
      do:  (sort.initialize' #());;;
      let: "$r0" := (let: "$a0" := #"no ClickHouse cluster discovered"%go in
      (FuncResolve errors.New [] #()) "$a0") in
      do:  ((GlobalVarAddr ErrEmptyCluster #()) <-[go.error] "$r0");;;
      let: "$r0" := (let: "$a0" := #"multiple ClickHouse clusters discovered; set cluster in Vault database config"%go in
      (FuncResolve errors.New [] #()) "$a0") in
      do:  ((GlobalVarAddr ErrAmbiguousCluster #()) <-[go.error] "$r0"))
      ).

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ChooseCluster_unfold :: FuncUnfold ChooseCluster [] (ChooseClusterⁱᵐᵖˡ);
  #[global] distinctNonEmpty_unfold :: FuncUnfold distinctNonEmpty [] (distinctNonEmptyⁱᵐᵖˡ);
  #[global] configuredWins_unfold :: FuncUnfold configuredWins [] (configuredWinsⁱᵐᵖˡ);
  #[global] discoveryRequired_unfold :: FuncUnfold discoveryRequired [] (discoveryRequiredⁱᵐᵖˡ);
  #[global] testChooseConfigured_unfold :: FuncUnfold testChooseConfigured [] (testChooseConfiguredⁱᵐᵖˡ);
  #[global] testChooseSingleDiscovery_unfold :: FuncUnfold testChooseSingleDiscovery [] (testChooseSingleDiscoveryⁱᵐᵖˡ);
  #[global] testChooseEmptyError_unfold :: FuncUnfold testChooseEmptyError [] (testChooseEmptyErrorⁱᵐᵖˡ);
  #[global] testChooseAmbiguous_unfold :: FuncUnfold testChooseAmbiguous [] (testChooseAmbiguousⁱᵐᵖˡ);
  #[global] import_sort_Assumption :: sort.Assumptions;
  #[global] import_strings_Assumption :: strings.Assumptions;
  #[global] import_errors_Assumption :: errors.Assumptions;
}.
End choose.
